package com.shopezone.userservice.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;


@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Users")
public class User {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute
    private String id;

    @DynamoDBAttribute
    @NotBlank(message = "Username is required")
    private String username;

    @DynamoDBAttribute
    private String password;

    @DynamoDBAttribute
    @Email(message = "Email is not valid")
    @NotBlank(message = "Email is required")
    private String email;

    @DynamoDBAttribute
    @NotBlank(message = "First name is required")
    private String firstName;

    @DynamoDBAttribute
    @NotBlank(message = "Last name is required")
    private String lastName;

    @DynamoDBAttribute
    private Date createdAt;

    @DynamoDBAttribute
    private Date updatedAt;

    @DynamoDBAttribute
    private Date lastLogin;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private UserRole role;
}

